# Examples
# https://concourse-ci.org/nodejs-example.html

resources:
  - name: repo
    type: git
    source:
      # TODO use private repo
      uri: https://github.com/matinaspatsos/php-slim-ci.git
      branch: concourse
  # See https://ddymko.medium.com/deploy-docker-images-with-concourse-396f7ad23fe2
  - name: app-php-image
    type: docker-image
    source:
      aws_access_key_id: ((aws-token))
      aws_secret_access_key: ((aws-secret))
      repository: ((php-slim-ecr-repo))
  - name: ci-image
    type: docker-image
    source:
      aws_access_key_id: ((aws-token))
      aws_secret_access_key: ((aws-secret))
      repository: ((php-slim-ci-ecr-repo))
  - name: bearer-sast-image
    type: docker-image
    source:
      repository: bearer/bearer

jobs:
  - name: build-ci-image
    # On serial groups: https://concourse-ci.org/jobs.html
    serial_groups:
      - unit-test
      - sast-scan
    plan:
      - get: repo
      - put: ci-image
        params:
          build: repo/ci
  - name: unit-test
    serial_groups:
      - unit-test
    plan:
      - get: repo
        trigger: true
      - get: ci-image
        trigger: true
      - task: install
        image: ci-image
        config:
          platform: linux
          inputs:
            - name: repo
          outputs:
            - name: dependencies
              path: repo/vendor
          run:
            path: composer
            args: ["install", "--no-interaction"]
            dir: repo
      - task: test
        image: ci-image
        config:
          platform: linux
          inputs:
            - name: repo
            - name: dependencies
              path: repo/vendor
          run:
            path: composer
            args: ["test"]
            dir: repo
  - name: sast-scan
    serial_groups:
      - sast-scan
    plan:
      - get: repo
        trigger: true
      - get: bearer-sast-image
      - task: scan
        image: bearer-sast-image
        config:
          platform: linux
          inputs:
            - name: repo
              path: /tmp/scan
          run:
            path: bearer
            args: ["scan", "/tmp/scan", "--debug"]
  # TODO Nginx build
  - name: build-php
    serial_groups:
      - unit-test
      - sast-scan
    plan:
      - get: repo
        passed:
          - unit-test
          - sast-scan
      - put: app-php-image
        params:
          build: repo/ci
